### ISSUE TITLE
Markoff cannot open files in the "Plain Text" format

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/Markoff#4]
To be honest, I just find this kind of amusing!

<img width="420" alt="capture 2016-03-01 at 10 47 14 am" src="https://cloud.githubusercontent.com/assets/147686/13412984/1a906916-df9b-11e5-8796-58f204baf257.PNG">

¯\\\_(ツ)\_/¯

Any files with the extension `.txt` are greyed-out in the file chooser, and I got this error using `open -a Markoff foo.txt`.

**Comment by balthisar** [comment]
+1, would be good fix.

**Comment by balthisar** [comment]
Quick fix is in #20 and will allow attempting to open any arbitrary filetype.

**Comment by kaishin** [comment]
@sharplet What would you expect when opening a .txt file? Be treated as if it was a Markdown file?

**Comment by sharplet** [comment]
Yes, more or less. I find it doesn't matter if it's not actually a markdown file and produces strange markup. It's helpful to have the flexibility to preview any plain text file.

**Comment by balthisar** [comment]
Lots of markdown files have other extensions, e.g., chained through other processors. For example my file.html.md.erb is a typical static site generator markdown file.

**Comment by kaishin** [comment]
@balthisar I have concerns about allowing any extension though. Will force us to handle errors and whatnot and it's not user-friendly when all files can be opened but only few will yield results.

**Comment by balthisar** [comment]
I could help take a look at this. As-is if I (for example) try to drag an image while allowing any file, it shows an appropriate warning (unable to parse the file).

To be more fancy you could tweak the `CFBundleDocumentTypes` entry to allow other extensions (pretty much any text extension might be acceptable; plain text is valid markdown for the most part).

I notice right now the existing entry uses `CFBundleTypeOSTypes` which is, while not officially deprecated, not all that useful for modern text files, especially in that it's allowing ????. Types and creators have been deprecated since 10.6 and are no longer even considered on the current deployment target.

The "modern" replacement is `LSItemContentTypes` which uses UTI's instead of type-creator codes. 

Then it's a decision on which UTI's to support. Using `public.txt` should be almost automatic. There's still the problem of the markdown engine trying to parse non-markdown, but again, that's not a bad thing. Most plain text will render just fine. Some of the other [system defined UTIs](https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) might be candidates, too.

John Gruber has even [indicated a preferred UTI for Markdown](http://daringfireball.net/linked/2011/08/05/markdown-uti) (UTIs aren't limited to Apple's system UTIs).

> net.daringfireball.markdown, which conforms to public.plain-text. The encoding should always be UTF-8.

So there's good support for arguing `public.plain-text` in addition to `public.txt` that I mentioned.

**Comment by vcavallo** [comment]
+1 The files in which I use markdown syntax are often `.txt`. For my (and I imagine many people's) workflows it makes the most sense to keep plain text in `txt` format and then let the context in which it's being used dictate how it should be rendered. (now I'm wondering why I use any extension at all...) 
The whole advantage of markdown is that I can use its syntax in non-fancy plain text files without any special handling and the syntax itself communicates the markup's intention - the markdown processors I look at them with are just a luxury.

**Comment by nickdunn** [comment]
I also hit this problem when trying to open Markdown files from Jekyll that I save as `.md.erb` because I process some dynamic snippets within the file.

**Comment by vcavallo** [comment]
@nickdunn Have you opened up those `.md.erb` files in any other markdown previewer? Like Mou or something?

**Comment by nickdunn** [comment]
Yes, they are just markdown (with a tiny bit of embedded ruby) but saved as `.erb`.

**Comment by vcavallo** [comment]
How do the Ruby code and erb tags look in the markdown? Like like plain
text? I don't have any similar files handy to look at myself but I'd assume
there would be some weirdness with the erb code not being fenced or
back-ticked and the characters being used by the markdown processor
erroneously.
On Fri, Mar 11, 2016 at 9:49 AM Nick Dunn <notifications@github.com> wrote:

> Yes, they are just markdown (with a tiny bit of embedded ruby) but saved
> as .erb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/Markoff/issues/4#issuecomment-195397032>.
>
-- 
Vinney Cavallo <http://vinneycavallo.com/>

**Comment by nickdunn** [comment]
Something simply like:

    Here is a paragraph.

    <% code('js') do %>
    Here is some JavaScript
    <% end %>

    Here is another paragraph.

Markoff renders the ERB as plain text as expected in this example. I'm not expecting Markoff to deal with this gracefully, but I'd like to be able to view the file as-is while editing the plain text parts.

**Comment by vcavallo** [comment]
I absolutely agree. Sorry for the tangent :)

On Fri, Mar 11, 2016 at 9:55 AM Nick Dunn <notifications@github.com> wrote:

> Something simply like:
>
> Here is a paragraph.
>
> <% code('js') do %>
> Here is some JavaScript
> <% end %>
>
> Here is another paragraph.
>
> Markoff renders the ERB as plain text as expected in this example. I'm not
> expecting Markoff to deal with this gracefully, but I'd like to be able to
> view the file as-is while editing the plain text parts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/Markoff/issues/4#issuecomment-195399995>.
>
-- 
Vinney Cavallo <http://vinneycavallo.com/>

**Comment by vcavallo** [comment]
:)
